### ISSUE TITLE
Beschreibung der Ramschtypen

### ISSUE THREAD

**Issue by joseph-wiesegger** [Jteve-Sobs/Schafkopf-Ramsch-Picker#2]
Guten Tag, soweit ich das verstehe, kann die App den Spieltyp ermitteln, falls niemand spielen möchte. Ist das korrekt?

Könnten Sie mir für jeden der unterstützten Spieltypen bitte kurz zukommen lassen, was genau es damit jeweils auf sich hat? Ich würde die Varianten in mein Buch (siehe https://raw.githubusercontent.com/joseph-wiesegger/schafkopf-buch/master/schafkopf_buch.pdf, Anhang A: Varianten) aufnehmen.

**Comment by Jteve-Sobs** [comment]
Hallo,
danke für das gezeigt Interesse und ihr Buch sieht interessant aus, muss ich mir genauer anschauen.
Die kleine Webseite war für eine Runde von mir gemeint, um bei einem Ramsch eine wenig Variation und Zufall in das Spiel zu bringen.

Gerne erkläre ich die Spielmodi:
Normal: Normaler Ramsch (Trümpfe wie Sauspiel und wer am wenigsten Augen hat am Ende)
10er eingereiht: Wie Normal, aber die Reihenfolge der Karten ist geändert (A K 10 9 8 7)
Trumpffrei: Ohne Trümpfe (Reihenfolge: A 10 K O U 9 8 7)
Trumpffrei 10er eingereiht: Komination aus Trumpffrei und 10er eingereiht
Geschoben: Man gibt 4 beliebige Karten an den linken Sitznachbar und bekommt 4 Karten vom rechten Sitznachbarn. Danach wird ein normaler Ramsch gespielt
Geschoben trumpffrei: Kombination aus Geschoben und trumpffrei
Der Alte muss: Der Spieler mit dem Eichel Ober muss ein Spiel (z.B. Ruf) ansagen

Ich hoffe, dass ich weiterhelfen konnte und werde auch mal die Varianten in ihrem Buch nachsehen

Gruß

**Comment by joseph-wiesegger** [comment]
Vielen Dank. Sollten Sie eine namentliche Erwähnung in meinem Buch wünschen, kontaktieren Sie mich bitte unter der im PDF angegebenen E-Mail-Adresse. Herzliche Grüße, Joseph Wiesegger
