### ISSUE TITLE
Setting all settings to zero yields in undefined selection when raffling

### ISSUE THREAD

**Issue by Jteve-Sobs** [Jteve-Sobs/Schafkopf-Ramsch-Picker#5]

**Comment by KeyK0n** [comment]
I'll fix.

**Comment by Jteve-Sobs** [comment]
Resolved with [#11](https://github.com/Jteve-Sobs/Schafkopf-Ramsch-Picker/commit/a3f4235f2ad357237ec2aee7d75c6fad17e8aff0)
